version: '3'
services:
  envoy:
    image: envoyproxy/envoy:v1.15.0
    container_name: envoy-grpc-proxy
    ports:
      - 9000:9000
    volumes:
      - ./proxy/envoy.yaml:/etc/envoy/envoy.yaml
    networks:
      - default

  youtube-info:
    build:
      context: ./backend/youtube-info
      dockerfile: ./Dockerfile
    image: docker.io/library/imakara-admin-youtube-info
    container_name: youtube-info
    environment:
      - YOUTUBE_INFO_API_KEY=
    networks:
      - default

  datastore:
    build:
      context: .
      dockerfile: ./Dockerfile.backend.datastore
    image: docker.io/library/imakara-admin-datastore
    container_name: datastore
    environment:
      - username=root
      - password=example
      - db_address=mongo
    networks:
      - db
      - default

# Use root/example as user/password credentials
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./configdb:/data/configdb
      - mongoDataStore:/data/db
    networks:
      - db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      - db

networks:
  db:
    driver: bridge
volumes:
  mongoDataStore:
    driver: local