FROM rust:1.71-buster
WORKDIR /temp

RUN wget "https://github.com/protocolbuffers/protobuf/releases/download/v23.4/protoc-23.4-linux-x86_64.zip" -O "protobuf.zip" && \
    unzip -o protobuf.zip -d protobuf && \
    chmod -R 755 protobuf/*
ENV PATH $PATH:/temp/protobuf/bin

COPY . .
WORKDIR /temp/backend/datastore
RUN cargo install --path .

CMD ["datastore"]