# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import common_pb2 as common__pb2


class StreamerInfoStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStreamerInfo = channel.unary_unary(
                '/imakara_admin_common.StreamerInfo/GetStreamerInfo',
                request_serializer=common__pb2.StreamerInfoRequest.SerializeToString,
                response_deserializer=common__pb2.StreamerInfoResponse.FromString,
                )


class StreamerInfoServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetStreamerInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StreamerInfoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStreamerInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStreamerInfo,
                    request_deserializer=common__pb2.StreamerInfoRequest.FromString,
                    response_serializer=common__pb2.StreamerInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'imakara_admin_common.StreamerInfo', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StreamerInfo(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetStreamerInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/imakara_admin_common.StreamerInfo/GetStreamerInfo',
            common__pb2.StreamerInfoRequest.SerializeToString,
            common__pb2.StreamerInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
