# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: streamer-info.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13streamer-info.proto\x12\rimakara_admin\"\"\n\x13StreamerInfoRequest\x12\x0b\n\x03url\x18\x01 \x01(\t\"\x8d\x01\n\x14StreamerInfoResponse\x12>\n\x13validation_response\x18\x01 \x01(\x0b\x32!.imakara_admin.ValidationResponse\x12\r\n\x05title\x18\x02 \x01(\t\x12\x12\n\navatar_url\x18\x03 \x01(\t\x12\x12\n\nchannel_id\x18\x04 \x01(\t\"U\n\x12ValidationResponse\x12/\n\x06result\x18\x01 \x01(\x0e\x32\x1f.imakara_admin.ValidationResult\x12\x0e\n\x06reason\x18\x02 \x01(\t*9\n\x10ValidationResult\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\x0b\n\x07\x46\x41ILURE\x10\x02\x32\x66\n\x08\x66rontend\x12Z\n\x0fGetStreamerInfo\x12\".imakara_admin.StreamerInfoRequest\x1a#.imakara_admin.StreamerInfoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'streamer_info_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_VALIDATIONRESULT']._serialized_start=305
  _globals['_VALIDATIONRESULT']._serialized_end=362
  _globals['_STREAMERINFOREQUEST']._serialized_start=38
  _globals['_STREAMERINFOREQUEST']._serialized_end=72
  _globals['_STREAMERINFORESPONSE']._serialized_start=75
  _globals['_STREAMERINFORESPONSE']._serialized_end=216
  _globals['_VALIDATIONRESPONSE']._serialized_start=218
  _globals['_VALIDATIONRESPONSE']._serialized_end=303
  _globals['_FRONTEND']._serialized_start=364
  _globals['_FRONTEND']._serialized_end=466
# @@protoc_insertion_point(module_scope)
