# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import streamer_info_pb2 as streamer__info__pb2


class frontendStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStreamerInfo = channel.unary_unary(
                '/imakara_admin.frontend/GetStreamerInfo',
                request_serializer=streamer__info__pb2.StreamerInfoRequest.SerializeToString,
                response_deserializer=streamer__info__pb2.StreamerInfoResponse.FromString,
                )


class frontendServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetStreamerInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_frontendServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStreamerInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStreamerInfo,
                    request_deserializer=streamer__info__pb2.StreamerInfoRequest.FromString,
                    response_serializer=streamer__info__pb2.StreamerInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'imakara_admin.frontend', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class frontend(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetStreamerInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/imakara_admin.frontend/GetStreamerInfo',
            streamer__info__pb2.StreamerInfoRequest.SerializeToString,
            streamer__info__pb2.StreamerInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
