// @generated by protoc-gen-connect-es v0.11.0 with parameter "target=ts"
// @generated from file proto/common.proto (package imakara_admin, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ListStreamerInfoRequest, ListStreamerInfoResponse, ListStreamersRequest, ListStreamersResponse, PutStreamerInfoRequest, PutStreamerInfoResponse, StreamerDetailRequest, StreamerDetailResponse, StreamerInfoRequest, StreamerInfoResponse } from "./common_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service imakara_admin.Dashboard
 */
export const Dashboard = {
  typeName: "imakara_admin.Dashboard",
  methods: {
    /**
     * @generated from rpc imakara_admin.Dashboard.ListStreamers
     */
    listStreamers: {
      name: "ListStreamers",
      I: ListStreamersRequest,
      O: ListStreamersResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc imakara_admin.Dashboard.GetStreamerInfo
     */
    getStreamerInfo: {
      name: "GetStreamerInfo",
      I: StreamerInfoRequest,
      O: StreamerInfoResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

/**
 * @generated from service imakara_admin.Common
 */
export const Common = {
  typeName: "imakara_admin.Common",
  methods: {
    /**
     * @generated from rpc imakara_admin.Common.GetStreamerDetail
     */
    getStreamerDetail: {
      name: "GetStreamerDetail",
      I: StreamerDetailRequest,
      O: StreamerDetailResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc imakara_admin.Common.ListStreamerInfo
     */
    listStreamerInfo: {
      name: "ListStreamerInfo",
      I: ListStreamerInfoRequest,
      O: ListStreamerInfoResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc imakara_admin.Common.PutStreamerInfo
     */
    putStreamerInfo: {
      name: "PutStreamerInfo",
      I: PutStreamerInfoRequest,
      O: PutStreamerInfoResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

