// @generated by protoc-gen-connect-es v0.11.0 with parameter "target=ts"
// @generated from file proto/common.proto (package imakara_admin_common, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { StreamerInfoRequest, StreamerInfoResponse } from "./common_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service imakara_admin_common.StreamerInfo
 */
export const StreamerInfo = {
  typeName: "imakara_admin_common.StreamerInfo",
  methods: {
    /**
     * @generated from rpc imakara_admin_common.StreamerInfo.GetStreamerInfo
     */
    getStreamerInfo: {
      name: "GetStreamerInfo",
      I: StreamerInfoRequest,
      O: StreamerInfoResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

