// @generated by protoc-gen-connect-es v0.11.0 with parameter "target=ts"
// @generated from file proto/frontend.proto (package imakara_admin_frontend, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ListStreamersRequest, ListStreamersResponse } from "./frontend_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service imakara_admin_frontend.Dashboard
 */
export const Dashboard = {
  typeName: "imakara_admin_frontend.Dashboard",
  methods: {
    /**
     * @generated from rpc imakara_admin_frontend.Dashboard.ListStreamers
     */
    listStreamers: {
      name: "ListStreamers",
      I: ListStreamersRequest,
      O: ListStreamersResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

