// @generated by protoc-gen-connect-es v0.11.0 with parameter "target=ts"
// @generated from file proto/streamer-info.proto (package imakara, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetDetailRequest, GetDetailResponse, ListProgramRequest, ListProgramResponse } from "./streamer-info_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service imakara.Program
 */
export const Program = {
  typeName: "imakara.Program",
  methods: {
    /**
     * @generated from rpc imakara.Program.List
     */
    list: {
      name: "List",
      I: ListProgramRequest,
      O: ListProgramResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc imakara.Program.GetDetail
     */
    getDetail: {
      name: "GetDetail",
      I: GetDetailRequest,
      O: GetDetailResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

