// @generated by protoc-gen-connect-es v0.11.0 with parameter "target=ts"
// @generated from file proto/streamer-info.proto (package imakara_admin, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { StreamerInfoRequest, StreamerInfoResponse } from "./streamer-info_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service imakara_admin.frontend
 */
export const frontend = {
  typeName: "imakara_admin.frontend",
  methods: {
    /**
     * @generated from rpc imakara_admin.frontend.GetStreamerInfo
     */
    getStreamerInfo: {
      name: "GetStreamerInfo",
      I: StreamerInfoRequest,
      O: StreamerInfoResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

